language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
sudo: required
before_install:
  - echo "extension = php_curl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install: composer install
after_script:
  - php vendor/bin/coveralls -v
