language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
sudo: required
before_install:
  - sudo apt-get update -qq
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo apt-get install -y php7-curl; fi
install: composer install
after_script:
  - php vendor/bin/coveralls -v
