language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y php-curl php-xml
install: composer install
after_script:
  - php vendor/bin/coveralls -v
